name: Continuous Integration (CI)

on: pull_request

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [shell]
    steps:
      - name: Checkout code.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check formatting.
        run: make check-${{ matrix.language }}-formatting
